# Introdução ao Pandas

A documentação oficial do Pandas possui bons tutoriais sobre a biblioteca, incluindo um tutorial de visão geral que pode ser acessado no link abaixo:

https://pandas.pydata.org/docs/user_guide/10min.html

## Obtendo informações básicas do dataset

In [25]:
import pandas as pd

# Leitura de um arquivo csv
file = "../data/diabetic_data.csv"
df = pd.read_csv(file)
type(df)

pandas.DataFrame

In [26]:
df

,encounter_id,patient_nbr,race,gender,age,weight,admission_type_id,discharge_disposition_id,admission_source_id,time_in_hospital,...,citoglipton,insulin,glyburide-metformin,glipizide-metformin,glimepiride-pioglitazone,metformin-rosiglitazone,metformin-pioglitazone,change,diabetesMed,readmitted
0,2278392,8222157,Caucasian,Female,[0-10),?,6,25,1,1,...,No,No,No,No,No,No,No,No,No,NO
1,149190,55629189,Caucasian,Female,[10-20),?,1,1,7,3,...,No,Up,No,No,No,No,No,Ch,Yes,>30
2,64410,86047875,AfricanAmerican,Female,[20-30),?,1,1,7,2,...,No,No,No,No,No,No,No,No,Yes,NO
3,500364,82442376,Caucasian,Male,[30-40),?,1,1,7,2,...,No,Up,No,No,No,No,No,Ch,Yes,NO
4,16680,42519267,Caucasian,Male,[40-50),?,1,1,7,1,...,No,Steady,No,No,No,No,No,Ch,Yes,NO
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,42801564,25911072,Caucasian,Female,[80-90),?,5,3,17,3,...,No,Steady,No,No,No,No,No,No,Yes,>30
9996,42802962,19316196,Caucasian,Female,[80-90),?,2,18,1,4,...,No,No,No,No,No,No,No,No,No,>30
9997,42805614,19316448,Caucasian,Male,[50-60),?,1,18,7,14,...,No,No,No,No,No,No,No,No,No,NO
9998,42808980,987381,Caucasian,Female,[50-60),?,1,1,7,2,...,No,No,No,No,No,No,No,No,No,NO
9999,42809670,23724657,Caucasian,Male,[80-90),?,1,3,17,4,...,No,No,No,No,No,No,No,No,Yes,NO

In [27]:
df.shape

(10000, 50)

In [28]:
# Tipos dos dados
df.dtypes

encounter_id                int64
patient_nbr                 int64
race                          str
gender                        str
age                           str
weight                        str
admission_type_id           int64
discharge_disposition_id    int64
admission_source_id         int64
time_in_hospital            int64
payer_code                    str
medical_specialty             str
num_lab_procedures          int64
num_procedures              int64
num_medications             int64
number_outpatient           int64
number_emergency            int64
number_inpatient            int64
diag_1                        str
diag_2                        str
diag_3                        str
number_diagnoses            int64
max_glu_serum                 str
A1Cresult                     str
metformin                     str
repaglinide                   str
nateglinide                   str
chlorpropamide                str
glimepiride                   str
acetohexamide                 str
glipizide                     str
glyburide                     str
tolbutamide                   str
pioglitazone                  str
rosiglitazone                 str
acarbose                      str
miglitol                      str
troglitazone                  str
tolazamide                    str
examide                       str
citoglipton                   str
insulin                       str
glyburide-metformin           str
glipizide-metformin           str
glimepiride-pioglitazone      str
metformin-rosiglitazone       str
metformin-pioglitazone        str
change                        str
diabetesMed                   str
readmitted                    str
dtype: object

In [29]:
# Informações básicas do dataset
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 50 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   encounter_id              10000 non-null  int64
 1   patient_nbr               10000 non-null  int64
 2   race                      10000 non-null  str
 3   gender                    10000 non-null  str
 4   age                       10000 non-null  str
 5   weight                    10000 non-null  str
 6   admission_type_id         10000 non-null  int64
 7   discharge_disposition_id  10000 non-null  int64
 8   admission_source_id       10000 non-null  int64
 9   time_in_hospital          10000 non-null  int64
 10  payer_code                10000 non-null  str
 11  medical_specialty         10000 non-null  str
 12  num_lab_procedures        10000 non-null  int64
 13  num_procedures            10000 non-null  int64
 14  num_medications           10000 non-null  int64
 15  number_outpatient         10000 non-null  int64
 16  number_emergency          10000 non-null  int64
 17  number_inpatient          10000 non-null  int64
 18  diag_1                    10000 non-null  str
 19  diag_2                    10000 non-null  str
 20  diag_3                    10000 non-null  str
 21  number_diagnoses          10000 non-null  int64
 22  max_glu_serum             885 non-null    str
 23  A1Cresult                 1886 non-null   str
 24  metformin                 10000 non-null  str
 25  repaglinide               10000 non-null  str
 26  nateglinide               10000 non-null  str
 27  chlorpropamide            10000 non-null  str
 28  glimepiride               10000 non-null  str
 29  acetohexamide             10000 non-null  str
 30  glipizide                 10000 non-null  str
 31  glyburide                 10000 non-null  str
 32  tolbutamide               10000 non-null  str
 33  pioglitazone              10000 non-null  str
 34  rosiglitazone             10000 non-null  str
 35  acarbose                  10000 non-null  str
 36  miglitol                  10000 non-null  str
 37  troglitazone              10000 non-null  str
 38  tolazamide                10000 non-null  str
 39  examide                   10000 non-null  str
 40  citoglipton               10000 non-null  str
 41  insulin                   10000 non-null  str
 42  glyburide-metformin       10000 non-null  str
 43  glipizide-metformin       10000 non-null  str
 44  glimepiride-pioglitazone  10000 non-null  str
 45  metformin-rosiglitazone   10000 non-null  str
 46  metformin-pioglitazone    10000 non-null  str
 47  change                    10000 non-null  str
 48  diabetesMed               10000 non-null  str
 49  readmitted                10000 non-null  str
dtypes: int64(13), str(37)
memory usage: 3.8 MB

In [30]:
# Valores únicos por coluna
df.nunique()

encounter_id                10000
patient_nbr                  8167
race                            6
gender                          2
age                            10
weight                         10
admission_type_id               7
discharge_disposition_id       14
admission_source_id            10
time_in_hospital               14
payer_code                      1
medical_specialty              44
num_lab_procedures            106
num_procedures                  7
num_medications                58
number_outpatient              12
number_emergency               11
number_inpatient               13
diag_1                        447
diag_2                        424
diag_3                        468
number_diagnoses                9
max_glu_serum                   3
A1Cresult                       3
metformin                       4
repaglinide                     4
nateglinide                     2
chlorpropamide                  4
glimepiride                     4
acetohexamide                   1
glipizide                       4
glyburide                       4
tolbutamide                     2
pioglitazone                    4
rosiglitazone                   4
acarbose                        3
miglitol                        1
troglitazone                    2
tolazamide                      2
examide                         1
citoglipton                     1
insulin                         4
glyburide-metformin             2
glipizide-metformin             1
glimepiride-pioglitazone        1
metformin-rosiglitazone         1
metformin-pioglitazone          1
change                          2
diabetesMed                     2
readmitted                      3
dtype: int64

In [31]:
# Estatísticas descritivas
df.describe()

,encounter_id,patient_nbr,admission_type_id,discharge_disposition_id,admission_source_id,time_in_hospital,num_lab_procedures,num_procedures,num_medications,number_outpatient,number_emergency,number_inpatient,number_diagnoses
count,1.000000e+04,1.000000e+04,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000
mean,2.531255e+07,2.501453e+07,2.439200,4.631700,6.635200,4.708200,46.631200,1.476400,14.924300,0.067200,0.042600,0.471500,6.755900
std,1.171356e+07,3.303636e+07,1.838761,6.632696,4.978795,3.154433,18.247512,1.765263,7.932532,0.463363,0.426619,1.017296,2.057119
min,1.252200e+04,1.350000e+02,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000,1.000000,0.000000,0.000000,0.000000,1.000000
25%,1.622375e+07,2.139876e+06,1.000000,1.000000,2.000000,2.000000,35.000000,0.000000,9.000000,0.000000,0.000000,0.000000,5.000000
50%,2.698506e+07,7.988742e+06,2.000000,1.000000,7.000000,4.000000,47.000000,1.000000,14.000000,0.000000,0.000000,0.000000,7.000000
75%,3.540126e+07,2.584620e+07,3.000000,6.000000,7.000000,6.000000,59.000000,2.000000,19.000000,0.000000,0.000000,1.000000,9.000000
max,4.280967e+07,1.151968e+08,8.000000,25.000000,20.000000,14.000000,114.000000,6.000000,62.000000,12.000000,22.000000,15.000000,9.000000

## Seleção de dados

In [32]:
time = df["time_in_hospital"]

time

0        1
1        3
2        2
3        2
4        1
        ..
9995     3
9996     4
9997    14
9998     2
9999     4
Name: time_in_hospital, Length: 10000, dtype: int64

In [33]:
# Cada coluna é uma série do pandas
type(time)

pandas.Series

In [34]:
# Seleção de múltiplas colunas
df_cols = df[["time_in_hospital", "num_lab_procedures", "num_procedures"]]

df_cols

      time_in_hospital  num_lab_procedures  num_procedures
0                    1                  41               0
1                    3                  59               0
2                    2                  11               5
3                    2                  44               1
4                    1                  51               0
...                ...                 ...             ...
9995                 3                  24               1
9996                 4                  43               2
9997                14                  49               6
9998                 2                  52               0
9999                 4                  28               1

[10000 rows x 3 columns]

In [35]:
# Seleção de todas as linhas nas quais o paciente ficou mais de 10 dias no hospital
df.loc[df["time_in_hospital"] > 10]

,encounter_id,patient_nbr,race,gender,age,weight,admission_type_id,discharge_disposition_id,admission_source_id,time_in_hospital,...,citoglipton,insulin,glyburide-metformin,glipizide-metformin,glimepiride-pioglitazone,metformin-rosiglitazone,metformin-pioglitazone,change,diabetesMed,readmitted
8,12522,48330783,Caucasian,Female,[80-90),?,2,1,4,13,...,No,Steady,No,No,No,No,No,Ch,Yes,NO
9,15738,63555939,Caucasian,Female,[90-100),?,3,3,4,12,...,No,Steady,No,No,No,No,No,Ch,Yes,NO
15,73578,86328819,AfricanAmerican,Male,[60-70),?,1,3,7,12,...,No,Up,No,No,No,No,No,Ch,Yes,NO
23,183930,107400762,Caucasian,Female,[80-90),?,2,6,1,11,...,No,No,No,No,No,No,No,No,No,>30
42,421194,96435585,Caucasian,Female,[70-80),?,2,1,1,13,...,No,Steady,No,No,No,No,No,Ch,Yes,>30
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9959,42669534,45144,Caucasian,Male,[10-20),?,2,1,1,14,...,No,Down,No,No,No,No,No,Ch,Yes,>30
9964,42693930,25420545,Caucasian,Female,[60-70),?,5,4,17,14,...,No,No,No,No,No,No,No,No,Yes,NO
9966,42694932,4941540,Caucasian,Male,[80-90),?,1,18,7,12,...,No,Up,No,No,No,No,No,Ch,Yes,>30
9984,42718740,76717512,Caucasian,Male,[70-80),?,1,3,7,11,...,No,No,No,No,No,No,No,No,No,NO
9997,42805614,19316448,Caucasian,Male,[50-60),?,1,18,7,14,...,No,No,No,No,No,No,No,No,No,NO

In [36]:
# Seleção do gênero dos pacientes que ficaram mais de 10 dias no hospital
df.loc[df["time_in_hospital"] > 10, "gender"]

8       Female
9       Female
15        Male
23      Female
42      Female
         ...
9959      Male
9964    Female
9966      Male
9984      Male
9997      Male
Name: gender, Length: 689, dtype: str

In [37]:
# Seleção das linhas associadas com a especialidade médica Cardiology ou Neurology
df[df["medical_specialty"].isin(["Cardiology", "Neurology"])]

,encounter_id,patient_nbr,race,gender,age,weight,admission_type_id,discharge_disposition_id,admission_source_id,time_in_hospital,...,citoglipton,insulin,glyburide-metformin,glipizide-metformin,glimepiride-pioglitazone,metformin-rosiglitazone,metformin-pioglitazone,change,diabetesMed,readmitted
17,84222,108662661,Caucasian,Female,[50-60),?,1,1,7,3,...,No,No,No,No,No,No,No,No,Yes,NO
26,236316,40523301,Caucasian,Male,[80-90),?,1,3,7,6,...,No,No,No,No,No,No,No,Ch,Yes,NO
29,252822,18196434,Caucasian,Female,[80-90),?,1,2,7,5,...,No,No,No,No,No,No,No,Ch,Yes,>30
35,325848,63023292,Caucasian,Female,[60-70),?,1,1,7,2,...,No,Down,No,No,No,No,No,Ch,Yes,>30
40,383430,80588529,Caucasian,Female,[70-80),?,1,2,7,1,...,No,Down,No,No,No,No,No,Ch,Yes,>30
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9944,42632598,114753042,Caucasian,Male,[70-80),?,6,6,17,12,...,No,No,No,No,No,No,No,No,No,NO
9950,42637896,2709846,Caucasian,Male,[70-80),?,1,1,7,3,...,No,No,No,No,No,No,No,No,No,NO
9951,42645030,4268547,Caucasian,Male,[70-80),?,3,1,1,1,...,No,No,No,No,No,No,No,No,No,NO
9975,42706956,64403964,Other,Female,[60-70),?,1,1,7,3,...,No,No,No,No,No,No,No,Ch,Yes,>30
9994,42793650,93364677,Caucasian,Female,[60-70),[75-100),6,1,17,1,...,No,No,No,No,No,No,No,No,No,NO

In [38]:
# Seleção das primeiras 100 linhas e das três primeiras colunas
df_sub = df.iloc[:100, :3]

df_sub

    encounter_id  patient_nbr             race
0        2278392      8222157        Caucasian
1         149190     55629189        Caucasian
2          64410     86047875  AfricanAmerican
3         500364     82442376        Caucasian
4          16680     42519267        Caucasian
..           ...          ...              ...
95       1195056     79549353        Caucasian
96       1195548    106343838        Caucasian
97       1212006     84981816        Caucasian
98       1257282     84488562            Other
99       1260216     92117574                ?

[100 rows x 3 columns]

# Valores ausentes

Usualmente, valores ausentes em Python são representados por `None` e `np.nan`.

In [39]:
val = None
type(val)

NoneType

In [40]:
import numpy as np

val = np.nan

# nan é do tipo float, definido no padrão IEEE 754 de representação de números de ponto flutuante
type(val)

float

In [41]:
# Segundo o padrão, nan não é igual a nenhum outro valor, inclusive a ele mesmo
np.nan == np.nan

False

In [42]:
# Qualquer operação com nan resulta em nan
2*np.nan

nan

In [43]:
# Uma série/coluna de inteiros não pode conter valores ausentes, portanto, o Pandas converte a série para float
s = pd.Series([2, 3, 4, np.nan])
s

0    2.0
1    3.0
2    4.0
3    NaN
dtype: float64

In [44]:
# Em uma série de strings, valores ausentes podem ser representados por None ou np.nan
s = pd.Series(["a", "b", "c", None, np.nan])
s

0      a
1      b
2      c
3    NaN
4    NaN
dtype: str

In [45]:
# Uma série de booleanos não pode conter valores ausentes, portanto, o Pandas converte a série para o tipo object
s1 = pd.Series([True, False])
s2 = pd.Series([True, False, np.nan])
print(s1.dtype, s2.dtype)

bool object

In [46]:
# Perigo! np.nan é considerado True em Python! Isso pode esconder valores ausentes.
s = pd.Series([True, False, np.nan], dtype=bool)
s

0     True
1    False
2     True
dtype: bool

Os tipos base do Pandas são `int`, `float`, `bool` e `str`.

O Pandas possui os tipos especiais `Int64`, `Float64`, `boolean` e `string`, que permitem a representação de valores ausentes com o tipo `pd.NA`.

In [47]:
s1 = pd.Series([2, 3, 4, np.nan], dtype="Int64")    
s2 = pd.Series(["a", "b", "c", None, np.nan], dtype="string")
s3 = pd.Series([True, False, np.nan], dtype=bool)

display(s1, s2, s3)

0       2
1       3
2       4
3    <NA>
dtype: Int64

0       a
1       b
2       c
3    <NA>
4    <NA>
dtype: string

0     True
1    False
2     True
dtype: bool

O leitor CSV do Pandas possui o parâmetro `na_values`, que permite a especificação de valores que devem ser interpretados como ausentes:

In [48]:
df = pd.read_csv(file, na_values=["?"])
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 50 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   encounter_id              10000 non-null  int64
 1   patient_nbr               10000 non-null  int64
 2   race                      9816 non-null   str
 3   gender                    10000 non-null  str
 4   age                       10000 non-null  str
 5   weight                    275 non-null    str
 6   admission_type_id         10000 non-null  int64
 7   discharge_disposition_id  10000 non-null  int64
 8   admission_source_id       10000 non-null  int64
 9   time_in_hospital          10000 non-null  int64
 10  payer_code                0 non-null      float64
 11  medical_specialty         6371 non-null   str
 12  num_lab_procedures        10000 non-null  int64
 13  num_procedures            10000 non-null  int64
 14  num_medications           10000 non-null  int64
 15  number_outpatient         10000 non-null  int64
 16  number_emergency          10000 non-null  int64
 17  number_inpatient          10000 non-null  int64
 18  diag_1                    9994 non-null   str
 19  diag_2                    9937 non-null   str
 20  diag_3                    9700 non-null   str
 21  number_diagnoses          10000 non-null  int64
 22  max_glu_serum             885 non-null    str
 23  A1Cresult                 1886 non-null   str
 24  metformin                 10000 non-null  str
 25  repaglinide               10000 non-null  str
 26  nateglinide               10000 non-null  str
 27  chlorpropamide            10000 non-null  str
 28  glimepiride               10000 non-null  str
 29  acetohexamide             10000 non-null  str
 30  glipizide                 10000 non-null  str
 31  glyburide                 10000 non-null  str
 32  tolbutamide               10000 non-null  str
 33  pioglitazone              10000 non-null  str
 34  rosiglitazone             10000 non-null  str
 35  acarbose                  10000 non-null  str
 36  miglitol                  10000 non-null  str
 37  troglitazone              10000 non-null  str
 38  tolazamide                10000 non-null  str
 39  examide                   10000 non-null  str
 40  citoglipton               10000 non-null  str
 41  insulin                   10000 non-null  str
 42  glyburide-metformin       10000 non-null  str
 43  glipizide-metformin       10000 non-null  str
 44  glimepiride-pioglitazone  10000 non-null  str
 45  metformin-rosiglitazone   10000 non-null  str
 46  metformin-pioglitazone    10000 non-null  str
 47  change                    10000 non-null  str
 48  diabetesMed               10000 non-null  str
 49  readmitted                10000 non-null  str
dtypes: float64(1), int64(13), str(36)
memory usage: 3.8 MB